version: "3.8"

services:
  # ---------- Infrastructure ----------
  zookeeper:
    image: bitnami/zookeeper:3.8
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:3
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092   # <‑‑ key line
    ports:
      - "9092:9092"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  # ---------- Microservice ----------
  math_service:
    build: .
    depends_on:
      - redis
      - kafka
    environment:
      - REDIS_URL=redis://redis:6379/0
      - KAFKA_BOOTSTRAP=kafka:9092
      - JWT_SECRET=change-me
    ports:
      - "5000:5000"
